[package]
name = "create-index"
version = "0.1.0"
authors = ["Kuan Yu <kuan.yu@student.uni-tuebingen.de>","Erik Schill <erik.schill@student.uni-tuebingen.de>"]

[dependencies]
conllx = "0.3.1"

[dev-dependencies]
quickcheck = "0.4.0"